export type Store = {
  markdown: string;
  html: string;
  css: string;
};

export const defaults: Store = {
  markdown:
    "# Mia Heidenstedt\nSoftware Developmer\n\n[📧 Email](mailto:career@i5h.eu) \n[🌍 Web](https://heidenstedt.org) \n[🛠GitHub](https://github.com/i5heu) \n[🐦Twitter]() \n[🔗LinkedIn](https://www.linkedin.com/in/mia-heidenstedt-7198ab145/ ) \n[🖇Xing](https://www.xing.com/profile/Mia_Heidenstedt/cv) \n\n## Most Important Skills \nGolang, TypeScript, SQL, Node\n\n### Skills\nC#, CSS, HTML, JavaScript, PHP (Symfony/Doctrine), Linux (Debian / Ubuntu), Nginx, MySql, CouchDB, Shell-Scripting, RocksDB, Selenium, Jest, Git, Mercurial,  Docker, Redis, IPFS, Shopify, Codeception, Selenium, Node, SQLite, Postgres, MySQL, Github-Actions, Google Cloud Functions, Svelte, Vue, Redux, Liquid, Rust, Go, Python, WASM, etc.\n\n## Relevant Experiance\n\n> ### Golang Developer <small>@ Fireball Labs GmbH</small>\n> April 2022 - October 2022  \n> ***Tech:*** Golang, Svelte, ClickHouse, MySQL, Typescript, Git\n\n\n> ### Frontend Developer <small>@ netshake GmbH</small>\n> March 2022 - April 2022  \n> ***Tech:*** JavaScript, PHP, Liquid, Shopify, Git, CSS\n\n\n> ### Apprenticeship Computer Science Expert <small>@ Intermetrics GmbH</small>\n> March 2018 - February 2021  \n> ***Tech:*** JavaScript, TypeScript, PHP (Symfony/Doctrine), Node, C#, Svelte, Vue, Redux, Mercurial, Google Cloud Functions, CSS, Jest, PHPUnit, Codeception, Selenium\n\n\n## Projects\n\n> ### Faultier-CV\n> Generated this CV  \n> https://github.com/i5heu/Faultier-CV\n\n> ### replication-simulator\n> Test the efficiency and effectiveness of different replication Algorithms.  \n> https://github.com/i5heu/replication-simulator\n\n> ### tor-simple-hidden-website \n> Create a hidden service with a static webpage in 1 Minute.  \n> https://github.com/i5heu/tor-simple-hidden-website",
  html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>CV</title>\n    <style>\n        {{css}}\n    </style>\n</head>\n<body>\n    {{markdown}}\n</body>\n</html>',
  css: "html {\n    font-family: Arial, Helvetica, sans-serif\n}\n\nbody {\n    padding: 1em 3em;\n}\n\na {\n    color: black;\n    text-decoration: none;\n    font-size: 1.2em;\n    margin-right: 7px;\n}\n\nblockquote {\n    border: 1px solid black;\n    padding: 5px;\n    border-radius: 5px;\n    margin: 1em 0;\n}\n\nblockquote h3 {\n    margin: 0;\n}\n\nblockquote p {\n    margin: 0.5em 0;\n}",
};
