export type Store = {
  markdown: string;
  html: string;
  css: string;
};

export const defaults: Store = {
  markdown:
    "# Mia Heidenstedt\nSoftware Developer\n\n[📧 Email](mailto:career@i5h.eu) \n[🌍 Web](https://heidenstedt.org) \n[🛠GitHub](https://github.com/i5heu)  \n[🐦Twitter](https://twitter.com/MiauPub) \n[🔗LinkedIn](https://www.linkedin.com/in/mia-heidenstedt-7198ab145/ ) \n[🖇Xing](https://www.xing.com/profile/Mia_Heidenstedt/cv)\n\n|   |   |\n|---|---|\n| Location:  |  Ulm, Germany |\n| Pronouns:  | she/her  |\n| Phone:  |  Available on request |\n\n## Skills\n### Most Important Skills \nGolang, TypeScript, SQL, Node\n#### Languages\nC#, CSS, HTML, JavaScript, PHP, Python, Liquid, Rust\n\n#### Frameworks\nSymfony, Doctrine, Selenium, Jest, Codeception, Svelte, Vue, Redux\n\n#### Databases\nMySql, CouchDB, RocksDB, PouchDB, Redis, SQLite, Postgres\n\n#### Systems\nLinux (Debian / Ubuntu), Nginx, Shell-Scripting, Git, Mercurial, Docker, IPFS, Shopify, Node, Github-Actions, Google Cloud Functions, WASM etc.\n\n### Hobbys\nProgramming, Reading, Sailing, Community Work\n\n## Relevant Experience\n\n> ### Golang Developer <small>@ Fireball Labs GmbH</small>\n> April 2022 - October 2022  \n> ***Tech:*** Golang, Svelte, ClickHouse, MySQL, Typescript, Git\n\n\n> ### Frontend Developer <small>@ netshake GmbH</small>\n> March 2021 - April 2022  \n> ***Tech:*** JavaScript, PHP, Liquid, Shopify, Git, CSS\n\n\n> ### Apprenticeship Computer Science Expert <small>@ Intermetrics GmbH</small>\n> March 2018 - February 2021  \n> ***Tech:*** JavaScript, TypeScript, PHP (Symfony/Doctrine), Node, C#, Svelte, Vue, Redux, Mercurial, Google Cloud Functions, CSS, Jest, PHPUnit, Codeception, Selenium\n\n\n## Projects\n\n> ### Faultier-CV\n> Generated this CV  \n> https://github.com/i5heu/Faultier-CV\n\n> ### replication-simulator\n> Test the efficiency and effectiveness of different replication Algorithms.  \n> https://github.com/i5heu/replication-simulator\n\n> ### tor-simple-hidden-website \n> Create a hidden service with a static webpage in 1 Minute.  \n> https://github.com/i5heu/tor-simple-hidden-website",
  html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>CV</title>\n    <style>\n        {{css}}\n    </style>\n</head>\n<body>\n    <img style="display: inline-block; float: right; height: 17em;" src="https://chaos.social/system/media_attachments/files/109/218/005/993/015/344/original/b2fc03161409acc8.jpeg">\n    {{markdown}}\n</body>\n</html>',
  css: "html {\n    font-family: Arial, Helvetica, sans-serif\n}\n\nbody {\n    padding: 3em 3em 1em 3em;\n}\n\nh1 {\n    margin-top: 0;\n}\n\nh4 {\n    margin-bottom: 0.2em;\n}\n\np {\n    margin-top: 0.3em;\n}\n\na {\n    color: black;\n    text-decoration: none;\n    font-size: 1.2em;\n    margin-right: 7px;\n}\n\nblockquote {\n    border: 1px solid black;\n    padding: 5px;\n    border-radius: 5px;\n    margin: 1em 0;\n}\n\nblockquote h3 {\n    margin: 0;\n}\n\nblockquote p {\n    margin: 0.5em 0;\n}\n\nblockquote a {\n    line-height: 2em;\n    font-size: 0.9em;\n    margin: 0.5em 0;\n}",
};
